#!/usr/bin/env python
# -*- coding: utf-8 -*-
import pyPdf
import nltk
import operator

def convertPdf2String(path):    
    pdf = pyPdf.PdfFileReader(file(path, "rb"))
    print pdf.getNumPages()
    content = ''
    for page in pdf.pages:
        content = content + page.extractText().encode("ascii", "ignore") 

    # tokenizer  = nltk.RegexpTokenizer(r'w+')
    tokens = nltk.word_tokenize(content)

    x = nltk.FreqDist(tokens)
    sorted_x = sorted(x.items(), key=operator.itemgetter(1),reverse=True)
    for a in sorted_x:
        print a[0],a[1]

if __name__ == "__main__":
    # nltk.download()    
    convertPdf2String("./Getting_Started_with_Arduino_3rd_Edition.pdf")

# ps2ascii ./Getting_Started_with_Arduino_3rd_Edition.pdf out.txt  #shell
 
